### ISSUE TITLE
Large header sizes from o365 causing "max call stack size exceeded"

### ISSUE THREAD

**Issue by bevis-plutoflume** [andris9/mailsplit#2]
For some strange reason Office 365 in some circumstances sends huge headers. I have one here from an email with many attachments at 106000 chars at over 30kb! This is an issue I just have to deal with, but mailsplitter doesn't seem to like it when trying to process such an email and fails at processLine call. Can this be fixed/any advice?

`RangeError: Maximum call stack size exceeded" stack_trace="RangeError: Maximum call stack size exceeded
    at new Uint8Array (native)at Buffer.subarray (native)
    at Buffer.slice (buffer.js:822:23)
    at iterateData (/mta_server/node_modules/mailsplit/lib/message-splitter.js:73:51)
    at processLine (/mta_server/node_modules/mailsplit/lib/message-splitter.js:79:36)
    at MessageSplitter.processLine (/mta_server/node_modules/mailsplit/lib/message-splitter.js:328:28)
    at iterateData (/mta_server/node_modules/mailsplit/lib/message-splitter.js:73:33)
    at processLine (/mta_server/node_modules/mailsplit/lib/message-splitter.js:79:36)
    at MessageSplitter.processLine (/mta_server/node_modules/mailsplit/lib/message-splitter.js:328:28)
    at iterateData (/mta_server/node_modules/mailsplit/lib/message-splitter.js:73:33)"`

**Comment by andris9** [comment]
Could you provide such a message for testing?

**Comment by andris9** [comment]
Verified and fixed in v4.1.1
